### ISSUE TITLE
Question: Ability to restrict to total requests/day per account

### ISSUE THREAD

**Issue by mbellmbell** [vladkens/twscrape#160]
Is there any way to restrict the number of requests for any account to X per day (or similar)? Right now, it seems like it's relying on the 50/15 restriction but then I have some accounts with 2,000+ requests/day and twitter is banning those. Wouldn't more accounts with fewer daily requests be safer?

**Comment by vladkens** [comment]
There is no such possibility and perhaps it is not planned.

The limits are not per account, but per api endpoint for account for time interval (per 15 min + per day). I mean that different methods have their own separate limits.

Writing these limits in code will be difficult, especially since it is impossible to track when Twitter changes its rules.

Also, the account will be banned after a while anyway, so there's not much point in protecting them.
