### ISSUE TITLE
cannot get more than 142 tweets from api.user_tweets

### ISSUE THREAD

**Issue by jt6677** [vladkens/twscrape#166]
I have 5 accounts logged in.
    api = API('accounts.db')
tweets = await gather(api.user_tweets(user_id, limit=2000))

I could only get 142 tweets back every time  before getting twscrape.queue_client:_check_rep:173 - Dependency error (request skipped): (131) Dependency: Internal error. (131)

what should I do? Thank you

**Comment by vladkens** [comment]
It's hard to tell what the problem is. It's an unrecognized Twitter bug at the moment.

- https://github.com/vladkens/twscrape/blob/9f34f03700b202bd7386091b0282271ae03ad516/twscrape/queue_client.py#L171
- https://github.com/vladkens/twscrape/pull/80

If you have managed to reproduce this error consistently - please share the request - this way it will be possible to investigate the reason.

**Comment by jt6677** [comment]
Thanks for the reply.       api = API('accounts.db')   tweets = await gather(api.user_tweets(user_id, limit=2000))          , I have 5 accounts logged in. It does not seem to rotate correctly. what is the recommended way to rotate each account?     I get 131 error every time I tried to scrap more tweet. It only returned 140ish tweets before error out.

**Comment by jt6677** [comment]
Using  exact code,  api = API('accounts.db')
tweets = await gather(api.user_tweets(user_id, limit=2000))             I tried 197785542 and could not get more than 150 tweet, and error out with 131.(ten tries)    HOWEVER, I tried 158439326 and I got 690.  Interesting....
