### ISSUE TITLE
Not scraping a thing anymore

### ISSUE THREAD

**Issue by ratobiajin** [vladkens/twscrape#188]
Hello! Thank you for your work! Now, login is successful to two accounts, but as there is no error, nor any tweets scraped either (it worked until today for more recent period, but now does not work to any period and any search keywords), i don't know what to do. This is the code on windows 11 cmd:
twscrape add_accounts "params.txt" "username:password:email:email_password"
twscrape login_accounts
twscrape search "ラトビア OR ラトヴィア OR ラトヴィヤ since:2023-01-01 until:2023-06-14" > 2023data4.json
nor it works in python idle. The uninstall and reinstall did not work. Please let me know.

**Comment by finiteautomata** [comment]
Same here. It seems that the issue is the query with `since` or `until`. For some reason, it is not returning anything

**Comment by vladkens** [comment]
Hi, @ratobiajin & @finiteautomata.

This is something with X.

This query still not working: https://x.com/search?q=%E3%83%A9%E3%83%88%E3%83%93%E3%82%A2%20OR%20%E3%83%A9%E3%83%88%E3%83%B4%E3%82%A3%E3%82%A2%20OR%20%E3%83%A9%E3%83%88%E3%83%B4%E3%82%A3%E3%83%A4%20since%3A2023-01-01%20until%3A2023-06-14&src=typed_query&f=live

But if I change date it working: https://x.com/search?q=%E3%83%A9%E3%83%88%E3%83%93%E3%82%A2%20OR%20%E3%83%A9%E3%83%88%E3%83%B4%E3%82%A3%E3%82%A2%20OR%20%E3%83%A9%E3%83%88%E3%83%B4%E3%82%A3%E3%83%A4%20since%3A2023-01-01%20until%3A2023-06-15&src=typed_query&f=live

So play with date range or use different [date format](https://github.com/igorbrigadir/twitter-advanced-search#:~:text=since%3A2021%2D12%2D31_23%3A59%3A59_UTC)
- full date
- or since_time
