### ISSUE TITLE
Get tweets and replies by specific date window

### ISSUE THREAD

**Issue by ernestng11** [vladkens/twscrape#79]
Hey all,

I looked through the API functions and noticed that there aren't any parameters where I can specify a specific date interval to pull data from. I am wondering if this feature will be something that can be added in the future. Thank you!

**Comment by ernestng11** [comment]
More specifically, I would like to see date parameters with user_tweets_and_replies

**Comment by vladkens** [comment]
Hi, @ernestng11. Twitter has no way to sort by date in the `user_tweets_and_replies` method, this method always returns approximately 3200 tweets in chronological order.

If you are interested in finding a particular user's tweets, you can use the normal `search` method by writing a query in the style: `from:user since:2021-12-31 until:2021-12-31`. But such a query will not return retweets.

More about filters here: https://github.com/igorbrigadir/twitter-advanced-search
