### ISSUE TITLE
mostRecent = await gather(api.user_tweets(user_id, limit=1))

### ISSUE THREAD

**Issue by 0xNyanDev** [vladkens/twscrape#84]
When I attempt to use this code and print the results, it fetches much more than 1 tweet. I am attempting to only return the most recent tweet, but it always returns 20-100 tweets no matter what I put as the limit.

```mostRecent = await gather(api.user_tweets(user_id, limit=1))```

I could work around this, to separate and return only the first item myself. but this will cause accounts to get rate limited MUCH faster, by an exponent of 20-100. Why is this happening? Shouldn't it be trivial to set a limit? I'm about to dive into the source code and see if I can fix it myself.

**Comment by vladkens** [comment]
Hi, @0xNyanDev.

limit may return more or less values, because Twitter gives results in batches (20, 40 depending on the method used). Limit is needed to stop data retrieval when a certain number of entities is reached.

Read more here: https://github.com/vladkens/twscrape/issues/26#issuecomment-1627716826
